### PR TITLE
don't apply Google font to codeblocks

### PR DESCRIPTION
**Pull request by diyachan**

### CODE REVIEW

**Comment by notmike101** [comment]
The only problem I can see with this approach is that if Discord ever changes the fonts or they are overwritten with a theme, this solution will have undesired effects.

Possibly use CSS selector `*:not(code)`? Not sure of the performance drawbacks that might have though.

**Comment by diyachan** [comment]
Hmmm yeah, I think using the :not(code) approach is better but I noticed something more: it still doesn't revert codeblocks with specified language on it (regardless of the :not selector usage)

updated my patch for it

**Comment by notmike101** [comment]
@diyachan Can you elaborate on what the `hljs` class is?

Is that a dynamic name of a class applied to code blocks?

**Comment by drashna** [comment]
> The only problem I can see with this approach is that if Discord ever changes the fonts or they are overwritten with a theme, this solution will have undesired effects.

Which has happened, or another plugin/theme I'm using is causing this to happen.

Also, would be nice to be able to set the code and non-code fonts separately.

**Pull request merged**
